{
 "title": "Load Test Monitoring for Kafka",
 "tags": [
  "k6",
  "influxdb"
 ],
 "time": { "from": "now-1m", "to": "now" },
 "panels": [
  {
   "title": "Total Number of Messages Produced",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "topic::tag" ], "type": "tag" }
     ],
     "measurement": "kafka_writer_message_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "ip.documents" }
     ]
    }
   ]
  },
  {
   "title": "cds.invoice(Messages Consumed)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "topic::tag" ], "type": "tag" }
     ],
     "measurement": "kafka_reader_message_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "cds.invoice" }
     ]
    }
   ]
  },
  {
   "title": "Total Number of Messages Produced",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "topic::tag" ], "type": "tag" }
     ],
     "measurement": "kafka_writer_message_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "ip.documents" }
     ]
    }
   ]
  },
  {
   "title": "Max Number of Active Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "vus_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Invoice.status(MessagesConsumed)",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "topic::tag" ], "type": "tag" }
     ],
     "measurement": "kafka_reader_message_count",
     "query": "SELECT * \nFROM \"k6\".\"autogen\".\"kafka_reader_message_count\" \nWHERE \"topic\" = 'invoice.status' ORDER BY time DESC \nLIMIT 5\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "cds.invoice" }
     ]
    }
   ]
  },
  {
   "title": "The Time it Takes Writing Messages",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "topic::tag" ], "type": "tag" }
     ],
     "measurement": "kafka_writer_write_seconds",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "ip.documents" }
     ]
    }
   ]
  },
  {
   "title": "Total Bytes Produced",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "topic::tag" ], "type": "tag" }
     ],
     "measurement": "kafka_writer_message_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "ip.documents" }
     ]
    }
   ]
  },
  {
   "title": "Total Bytes Produced",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "topic::tag" ], "type": "tag" }
     ],
     "measurement": "kafka_writer_message_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "ip.documents" }
     ]
    }
   ]
  }
 ]
}