{
 "title": "Load Test Monitoring for Kafka",
 "tags": [
  "k6",
  "influxdb"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Messages Produced(ip.documents)",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "topic::tag" ], "type": "tag" }
     ],
     "measurement": "kafka_writer_message_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "ip.documents" }
     ]
    }
   ]
  },
  {
   "title": " MessagesConsumed(invoice.status)",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "topic::tag" ], "type": "tag" }
     ],
     "measurement": "kafka_reader_message_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "invoice.status" }
     ]
    }
   ]
  },
  {
   "title": "Total Bytes Produced",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "topic::tag" ], "type": "tag" }
     ],
     "measurement": "kafka_writer_message_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "ip.documents" }
     ]
    }
   ]
  },
  {
   "title": "The Time it Takes Writing Messages",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "topic::tag" ], "type": "tag" }
     ],
     "measurement": "kafka_writer_write_seconds",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "ip.documents" }
     ]
    }
   ]
  },
  {
   "title": "reader fetches batches of messages.",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "topic::tag" ], "type": "tag" }
     ],
     "measurement": "kafka_reader_fetch_wait_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "invoice.status" }
     ]
    }
   ]
  },
  {
   "title": "Time it takes to connect to the reader in a Kafka cluster.",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "topic::tag" ], "type": "tag" }
     ],
     "measurement": "kafka_reader_dial_seconds",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "invoice.status" }
     ]
    }
   ]
  },
  {
   "title": "Errors occurred when writing.",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "topic::tag" ], "type": "tag" }
     ],
     "measurement": "kafka_writer_error_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "ip.documents" }
     ]
    }
   ]
  },
  {
   "title": "Max Number of Active Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "vus_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Errors occurred when reading.",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "topic::tag" ], "type": "tag" }
     ],
     "measurement": "kafka_reader_error_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "invoice.status" }
     ]
    }
   ]
  },
  {
   "title": "queue capacity while reading batch of messages.",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "topic::tag" ], "type": "tag" }
     ],
     "measurement": "kafka_reader_queue_capacity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "invoice.status" }
     ]
    }
   ]
  },
  {
   "title": "Maximum number of attempts at writing messages.",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "topic::tag" ], "type": "tag" }
     ],
     "measurement": "kafka_writer_attempts_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "ip.documents" }
     ]
    }
   ]
  }
 ]
}